# Generated by Django 5.0 on 2023-12-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
