# Generated by Django 5.0 on 2023-12-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_link_original_url_alter_link_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
