# Generated by Django 5.0 on 2023-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_link_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(),
        ),
    ]
